include: package:lint/analysis_options.yaml

linter:
  rules:
  # style
    # camel_case_types: true
    avoid_catching_errors: true
    avoid_empty_else: true
    avoid_returning_null: true
    avoid_null_checks_in_equality_operators: true
    empty_statements: true
    empty_catches: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_overrides: true
    unnecessary_lambdas: true
    unnecessary_brace_in_string_interps: true
  # formatting
    # lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: true

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error